numprocs=128

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 


Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BP_cNAC_0 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_BTC_cNAC_1 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_NBC_cNAC_2 cNAC_L6NGC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_SSC_cADpyr_3 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_4 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_TPC_cADpyr_5 cADpyr_L4TPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
L4_UPC_cADpyr_6 cADpyr_L4UPC
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py

Start time:  2025-04-06 22:54:25.869803
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py
odict_keys(['E->E_A', 'E->E_B', 'E->E_C', 'E->E_D', 'E->I', 'I->E', 'thal_VPM_sTC_L4_SSC_cADpyr_3', 'thal_VPM_sTC_L4_TPC_cADpyr_4', 'thal_VPM_sTC_L4_TPC_cADpyr_5', 'thal_VPM_sTC_L4_UPC_cADpyr_6', 'thal_VPM_sTC_L4_BP_cNAC_0', 'thal_VPM_sTC_L4_BTC_cNAC_1', 'thal_VPM_sTC_L4_NBC_cNAC_2'])
Importing netParams from /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_netParams.py

Creating network of 8 cell populations on 128 hosts...
  Number of cells on node 108: 8 
  Number of cells on node 119: 8 
  Number of cells on node 96: 8 
  Number of cells on node 11: 9 
  Number of cells on node 66: 8 
  Number of cells on node 16: 9 
  Number of cells on node 7: 9 
  Number of cells on node 75: 8 
  Number of cells on node 98: 8 
  Number of cells on node 73: 8 
  Number of cells on node 52: 8 
  Number of cells on node 36: 8 
  Number of cells on node 102: 8 
  Number of cells on node 41: 8 
  Number of cells on node 94: 8 
  Number of cells on node 54: 8 
  Number of cells on node 82: 8 
  Number of cells on node 37: 8 
  Number of cells on node 101: 8 
  Number of cells on node 122: 8 
  Number of cells on node 10: 9 
  Number of cells on node 124: 8 
  Number of cells on node 3: 9 
  Number of cells on node 77: 8 
  Number of cells on node 1: 9 
  Number of cells on node 76: 8 
  Number of cells on node 47: 8 
  Number of cells on node 93: 8 
  Number of cells on node 28: 8 
  Number of cells on node 114: 8 
  Number of cells on node 64: 8 
  Number of cells on node 13: 9 
  Number of cells on node 85: 8 
  Number of cells on node 45: 8 
  Number of cells on node 115: 8 
  Number of cells on node 112: 8 
  Number of cells on node 59: 8 
  Number of cells on node 117: 8 
  Number of cells on node 46: 8 
  Number of cells on node 62: 8 
  Number of cells on node 87: 8 
  Number of cells on node 26: 8 
  Number of cells on node 43: 8 
  Number of cells on node 89: 8 
  Number of cells on node 69: 8 
  Number of cells on node 81: 8 
  Number of cells on node 15: 9 
  Number of cells on node 103: 8 
  Number of cells on node 12: 9 
  Number of cells on node 99: 8 
  Number of cells on node 121: 8 
  Number of cells on node 18: 9 
  Number of cells on node 53: 8 
  Number of cells on node 125: 8 
  Number of cells on node 111: 8 
  Number of cells on node 123: 8 
  Number of cells on node 90: 8 
  Number of cells on node 95: 8 
  Number of cells on node 33: 8 
  Number of cells on node 42: 8 
  Number of cells on node 34: 8 
  Number of cells on node 6: 9 
  Number of cells on node 67: 8 
  Number of cells on node 105: 8 
  Number of cells on node 25: 8 
  Number of cells on node 100: 8 
  Number of cells on node 48: 8 
  Number of cells on node 126: 8 
  Number of cells on node 32: 8 
  Number of cells on node 91: 8 
  Number of cells on node 97: 8 
  Number of cells on node 21: 9 
  Number of cells on node 113: 8 
  Number of cells on node 63: 8 
  Number of cells on node 4: 9 
  Number of cells on node 20: 9 
  Number of cells on node 29: 8 
  Number of cells on node 39: 8 
  Number of cells on node 50: 8 
  Number of cells on node 51: 8 
  Number of cells on node 70: 8 
  Number of cells on node 31: 8 
  Number of cells on node 107: 8 
  Number of cells on node 78: 8 
  Number of cells on node 22: 9 
  Number of cells on node 61: 8 
  Number of cells on node 35: 8 
  Number of cells on node 92: 8 
  Number of cells on node 38: 8 
  Number of cells on node 17: 9 
  Number of cells on node 60: 8 
  Number of cells on node 68: 8 
  Number of cells on node 79: 8 
  Number of cells on node 110: 8 
  Number of cells on node 49: 8 
  Number of cells on node 106: 8 
  Number of cells on node 118: 8 
  Number of cells on node 80: 8 
  Number of cells on node 55: 8 
  Number of cells on node 5: 9 
  Number of cells on node 74: 8 
  Number of cells on node 71: 8 
  Number of cells on node 0: 9 
  Number of cells on node 2: 9 
  Number of cells on node 27: 8 
  Number of cells on node 84: 8 
  Number of cells on node 83: 8 
  Number of cells on node 19: 9 
  Number of cells on node 58: 8 
  Number of cells on node 9: 9 
  Number of cells on node 127: 8 
  Number of cells on node 57: 8 
  Number of cells on node 14: 9 
  Number of cells on node 109: 8 
  Number of cells on node 23: 9 
  Number of cells on node 65: 8 
  Number of cells on node 86: 8 
  Number of cells on node 30: 8 
  Number of cells on node 44: 8 
  Number of cells on node 116: 8 
  Number of cells on node 40: 8 
  Number of cells on node 8: 9 
  Number of cells on node 24: 8 
  Number of cells on node 88: 8 
  Number of cells on node 104: 8 
  Number of cells on node 120: 8 
  Number of cells on node 56: 8 
  Number of cells on node 72: 8 
  Done; cell creation time = 0.61 s.
Making connections...
  Number of connections on node 89: 1469 
  Number of synaptic contacts on node 89: 7089 
  Number of connections on node 109: 1477 
  Number of synaptic contacts on node 109: 7085 
  Number of connections on node 91: 1478 
  Number of synaptic contacts on node 91: 7109 
  Number of connections on node 113: 1484 
  Number of synaptic contacts on node 113: 7141 
  Number of connections on node 87: 1491 
  Number of synaptic contacts on node 87: 7134 
  Number of connections on node 85: 1483 
  Number of synaptic contacts on node 85: 7131 
  Number of connections on node 95: 1472 
  Number of synaptic contacts on node 95: 7098 
  Number of connections on node 99: 1492 
  Number of synaptic contacts on node 99: 7172 
  Number of connections on node 101: 1493 
  Number of synaptic contacts on node 101: 7154 
  Number of connections on node 105: 1481 
  Number of synaptic contacts on node 105: 7125 
  Number of connections on node 82: 1504 
  Number of synaptic contacts on node 82: 7208 
  Number of connections on node 86: 1476 
  Number of connections on node 103: 1497 
  Number of synaptic contacts on node 103: 7138 
  Number of synaptic contacts on node 86: 7068 
  Number of connections on node 93: 1490 
  Number of synaptic contacts on node 93: 7152 
  Number of connections on node 111: 1493 
  Number of synaptic contacts on node 111: 7189 
  Number of connections on node 94: 1477 
  Number of connections on node 107: 1508 
  Number of synaptic contacts on node 107: 7262 
  Number of synaptic contacts on node 94: 7092 
  Number of connections on node 106: 1508 
  Number of synaptic contacts on node 106: 7213 
  Number of connections on node 97: 1509 
  Number of synaptic contacts on node 97: 7286 
  Number of connections on node 100: 1483 
  Number of synaptic contacts on node 100: 7138 
  Number of connections on node 98: 1480 
  Number of synaptic contacts on node 98: 7122 
  Number of connections on node 83: 1502 
  Number of synaptic contacts on node 83: 7223 
  Number of connections on node 115: 1526 
  Number of synaptic contacts on node 115: 7281 
  Number of connections on node 110: 1473 
  Number of connections on node 92: 1490 
  Number of synaptic contacts on node 92: 7166 
  Number of synaptic contacts on node 110: 7108 
  Number of connections on node 96: 1499 
  Number of synaptic contacts on node 96: 7207 
  Number of connections on node 112: 1473 
  Number of synaptic contacts on node 112: 7094 
  Number of connections on node 104: 1493 
  Number of synaptic contacts on node 104: 7196 
  Number of connections on node 108: 1487 
  Number of connections on node 114: 1498 
  Number of synaptic contacts on node 114: 7211 
  Number of synaptic contacts on node 108: 7192 
  Number of connections on node 90: 1494 
  Number of synaptic contacts on node 90: 7171 
  Number of connections on node 88: 1507 
  Number of synaptic contacts on node 88: 7203 
  Number of connections on node 121: 1470 
  Number of synaptic contacts on node 121: 7670 
  Number of connections on node 84: 1491 
  Number of synaptic contacts on node 84: 7197 
  Number of connections on node 102: 1493 
  Number of synaptic contacts on node 102: 7210 
  Number of connections on node 81: 1591 
  Number of synaptic contacts on node 81: 7434 
  Number of connections on node 117: 1481 
  Number of synaptic contacts on node 117: 7654 
  Number of connections on node 125: 1515 
  Number of synaptic contacts on node 125: 7791 
  Number of connections on node 123: 1498 
  Number of synaptic contacts on node 123: 7782 
  Number of connections on node 122: 1487 
  Number of synaptic contacts on node 122: 7665 
  Number of connections on node 120: 1482 
  Number of synaptic contacts on node 120: 7671 
  Number of connections on node 127: 1497 
  Number of synaptic contacts on node 127: 7793 
  Number of connections on node 116: 1471 
  Number of connections on node 119: 1498 
  Number of synaptic contacts on node 119: 7782 
  Number of synaptic contacts on node 116: 7701 
  Number of connections on node 124: 1492 
  Number of synaptic contacts on node 124: 7722 
  Number of connections on node 118: 1486 
  Number of synaptic contacts on node 118: 7725 
  Number of connections on node 126: 1491 
  Number of synaptic contacts on node 126: 7740 
  Number of connections on node 80: 1636 
  Number of synaptic contacts on node 80: 7646 
  Number of connections on node 73: 1753 
  Number of synaptic contacts on node 73: 8278 
  Number of connections on node 67: 1773 
  Number of synaptic contacts on node 67: 8387 
  Number of connections on node 75: 1771 
  Number of synaptic contacts on node 75: 8374 
  Number of connections on node 77: 1768 
  Number of synaptic contacts on node 77: 8372 
  Number of connections on node 71: 1780 
  Number of synaptic contacts on node 71: 8443 
  Number of connections on node 65: 1772 
  Number of synaptic contacts on node 65: 8384 
  Number of connections on node 62: 1764 
  Number of synaptic contacts on node 62: 8318 
  Number of connections on node 69: 1784 
  Number of synaptic contacts on node 69: 8420 
  Number of connections on node 66: 1770 
  Number of synaptic contacts on node 66: 8322 
  Number of connections on node 64: 1767 
  Number of synaptic contacts on node 64: 8348 
  Number of connections on node 79: 1773 
  Number of synaptic contacts on node 79: 8373 
  Number of connections on node 70: 1771 
  Number of synaptic contacts on node 70: 8346 
  Number of connections on node 60: 1786 
  Number of synaptic contacts on node 60: 8454 
  Number of connections on node 72: 1781 
  Number of synaptic contacts on node 72: 8369 
  Number of connections on node 74: 1786 
  Number of synaptic contacts on node 74: 8419 
  Number of connections on node 76: 1788 
  Number of synaptic contacts on node 76: 8418 
  Number of connections on node 61: 1797 
  Number of synaptic contacts on node 61: 8480 
  Number of connections on node 63: 1787 
  Number of synaptic contacts on node 63: 8485 
  Number of connections on node 78: 1781 
  Number of synaptic contacts on node 78: 8439 
  Number of connections on node 68: 1786 
  Number of synaptic contacts on node 68: 8489 
  Number of connections on node 57: 1779 
  Number of synaptic contacts on node 57: 8947 
  Number of connections on node 49: 1796 
  Number of synaptic contacts on node 49: 8956 
  Number of connections on node 48: 1785 
  Number of synaptic contacts on node 48: 8972 
  Number of connections on node 52: 1790 
  Number of synaptic contacts on node 52: 8945 
  Number of connections on node 54: 1782 
  Number of synaptic contacts on node 54: 8942 
  Number of connections on node 46: 1789 
  Number of synaptic contacts on node 46: 8942 
  Number of connections on node 51: 1788 
  Number of synaptic contacts on node 51: 8925 
  Number of connections on node 56: 1796 
  Number of synaptic contacts on node 56: 9005 
  Number of connections on node 53: 1797 
  Number of synaptic contacts on node 53: 8959 
  Number of connections on node 59: 1795 
  Number of synaptic contacts on node 59: 8967 
  Number of connections on node 47: 1774 
  Number of synaptic contacts on node 47: 8862 
  Number of connections on node 50: 1800 
  Number of synaptic contacts on node 50: 9017 
  Number of connections on node 45: 1798 
  Number of synaptic contacts on node 45: 9025 
  Number of connections on node 43: 1799 
  Number of synaptic contacts on node 43: 9063 
  Number of connections on node 44: 1795 
  Number of synaptic contacts on node 44: 9030 
  Number of connections on node 55: 1808 
  Number of synaptic contacts on node 55: 9083 
  Number of connections on node 58: 1800 
  Number of synaptic contacts on node 58: 9101 
  Number of connections on node 2: 2053 
  Number of synaptic contacts on node 2: 10105 
  Number of connections on node 24: 2057 
  Number of synaptic contacts on node 24: 10129 
  Number of connections on node 26: 2055 
  Number of synaptic contacts on node 26: 10167 
  Number of connections on node 11: 2055 
  Number of synaptic contacts on node 11: 10175 
  Number of connections on node 7: 2048 
  Number of synaptic contacts on node 7: 10090 
  Number of connections on node 18: 2060 
  Number of synaptic contacts on node 18: 10156 
  Number of connections on node 8: 2050 
  Number of synaptic contacts on node 8: 10145 
  Number of connections on node 16: 2056 
  Number of synaptic contacts on node 16: 10244 
  Number of connections on node 41: 2051 
  Number of synaptic contacts on node 41: 10112 
  Number of connections on node 34: 2052 
  Number of synaptic contacts on node 34: 10177 
  Number of connections on node 22: 2068 
  Number of synaptic contacts on node 22: 10297 
  Number of connections on node 1: 2053 
  Number of synaptic contacts on node 1: 10186 
  Number of connections on node 6: 2081 
  Number of synaptic contacts on node 6: 10240 
  Number of connections on node 15: 2070 
  Number of connections on node 32: 2048 
  Number of synaptic contacts on node 32: 10154 
  Number of synaptic contacts on node 15: 10256 
  Number of connections on node 36: 2076 
  Number of synaptic contacts on node 36: 10216 
  Number of connections on node 0: 2070 
  Number of synaptic contacts on node 0: 10242 
  Number of connections on node 13: 2065 
  Number of synaptic contacts on node 13: 10217 
  Number of connections on node 33: 2065 
  Number of connections on node 19: 2078 
  Number of synaptic contacts on node 19: 10258 
  Number of connections on node 30: 2062 
  Number of synaptic contacts on node 30: 10258 
  Number of synaptic contacts on node 33: 10172 
  Number of connections on node 4: 2083 
  Number of synaptic contacts on node 4: 10366 
  Number of connections on node 17: 2065 
  Number of synaptic contacts on node 17: 10258 
  Number of connections on node 40: 2067 
  Number of synaptic contacts on node 40: 10218 
  Number of connections on node 10: 2058 
  Number of synaptic contacts on node 10: 10259 
  Number of connections on node 14: 2089 
  Number of synaptic contacts on node 14: 10298 
  Number of connections on node 31: 2077 
  Number of synaptic contacts on node 31: 10223 
  Number of connections on node 25: 2072 
  Number of synaptic contacts on node 25: 10237 
  Number of connections on node 37: 2051 
  Number of synaptic contacts on node 37: 10165 
  Number of connections on node 12: 2086 
  Number of synaptic contacts on node 12: 10309 
  Number of connections on node 20: 2095 
  Number of synaptic contacts on node 20: 10329 
  Number of connections on node 23: 2062 
  Number of synaptic contacts on node 23: 10220 
  Number of connections on node 39: 2072 
  Number of synaptic contacts on node 39: 10282 
  Number of connections on node 42: 2067 
  Number of synaptic contacts on node 42: 10253 
  Number of connections on node 29: 2085 
  Number of synaptic contacts on node 29: 10344 
  Number of connections on node 27: 2079 
  Number of synaptic contacts on node 27: 10351 
  Number of connections on node 28: 2105 
  Number of synaptic contacts on node 28: 10413 
  Number of connections on node 9: 2101 
  Number of connections on node 3: 2090 
  Number of synaptic contacts on node 3: 10285 
  Number of synaptic contacts on node 9: 10387 
  Number of connections on node 21: 2097 
  Number of synaptic contacts on node 21: 10353 
  Number of connections on node 38: 2106 
  Number of synaptic contacts on node 38: 10392 
  Number of connections on node 35: 2109 
  Number of synaptic contacts on node 35: 10413 
  Number of connections on node 5: 2095 
  Number of synaptic contacts on node 5: 10343 
  Done; cell connection time = 1.20 s.
Adding stims...
  Number of stims on node 99: 120 
  Number of stims on node 113: 120 
  Number of stims on node 127: 120 
  Number of stims on node 82: 120 
  Number of stims on node 119: 120 
  Number of stims on node 93: 120 
  Number of stims on node 106: 120 
  Number of stims on node 115: 120 
  Number of stims on node 123: 120 
  Number of stims on node 116: 120 
  Number of stims on node 83: 120 
  Number of stims on node 91: 120 
  Number of stims on node 107: 120 
  Number of stims on node 94: 120 
  Number of stims on node 126: 120 
  Number of stims on node 121: 120 
  Number of stims on node 103: 120 
  Number of stims on node 117: 120 
  Number of stims on node 85: 120 
  Number of stims on node 111: 120 
  Number of stims on node 105: 120 
  Number of stims on node 87: 120 
  Number of stims on node 125: 120 
  Number of stims on node 101: 120 
  Number of stims on node 109: 120 
  Number of stims on node 92: 120 
  Number of stims on node 89: 120 
  Number of stims on node 104: 120 
  Number of stims on node 80: 120 
  Number of stims on node 96: 120 
  Number of stims on node 81: 120 
  Number of stims on node 114: 120 
  Number of stims on node 95: 120 
  Number of stims on node 110: 120 
  Number of stims on node 84: 120 
  Number of stims on node 97: 120 
  Number of stims on node 122: 120 
  Number of stims on node 120: 120 
  Number of stims on node 112: 120 
  Number of stims on node 124: 120 
  Number of stims on node 100: 120 
  Number of stims on node 118: 120 
  Number of stims on node 102: 120 
  Number of stims on node 88: 120 
  Number of stims on node 108: 120 
  Number of stims on node 90: 120 
  Number of stims on node 98: 120 
  Number of stims on node 86: 120 
  Number of stims on node 77: 140 
  Number of stims on node 27: 140 
  Number of stims on node 15: 140 
  Number of stims on node 75: 140 
  Number of stims on node 11: 140 
  Number of stims on node 1: 140 
  Number of stims on node 20: 140 
  Number of stims on node 8: 140 
  Number of stims on node 65: 140 
  Number of stims on node 6: 140 
  Number of stims on node 21: 140 
  Number of stims on node 5: 140 
  Number of stims on node 24: 140 
  Number of stims on node 17: 140 
  Number of stims on node 4: 140 
  Number of stims on node 68: 140 
  Number of stims on node 67: 140 
  Number of stims on node 16: 140 
  Number of stims on node 0: 140 
  Number of stims on node 62: 140 
  Number of stims on node 12: 140 
  Number of stims on node 57: 140 
  Number of stims on node 58: 140 
  Number of stims on node 18: 140 
  Number of stims on node 22: 140 
  Number of stims on node 59: 140 
  Number of stims on node 7: 140 
  Number of stims on node 37: 140 
  Number of stims on node 56: 140 
  Number of stims on node 13: 140 
  Number of stims on node 2: 140 
  Number of stims on node 47: 140 
  Number of stims on node 79: 140 
  Number of stims on node 73: 140 
  Number of stims on node 33: 140 
  Number of stims on node 64: 140 
  Number of stims on node 71: 140 
  Number of stims on node 69: 140 
  Number of stims on node 60: 140 
  Number of stims on node 51: 140 
  Number of stims on node 53: 140 
  Number of stims on node 61: 140 
  Number of stims on node 36: 140 
  Number of stims on node 9: 140 
  Number of stims on node 46: 140 
  Number of stims on node 14: 140 
  Number of stims on node 70: 140 
  Number of stims on node 78: 140 
  Number of stims on node 44: 140 
  Number of stims on node 19: 140 
  Number of stims on node 43: 140 
  Number of stims on node 55: 140 
  Number of stims on node 54: 140 
  Number of stims on node 45: 140 
  Number of stims on node 49: 140 
  Number of stims on node 23: 140 
  Number of stims on node 63: 140 
  Number of stims on node 76: 140 
  Number of stims on node 72: 140 
  Number of stims on node 48: 140 
  Number of stims on node 25: 140 
  Number of stims on node 3: 140 
  Number of stims on node 74: 140 
  Number of stims on node 66: 140 
  Number of stims on node 50: 140 
  Number of stims on node 52: 140 
  Number of stims on node 35: 140 
  Number of stims on node 31: 140 
  Number of stims on node 39: 140 
  Number of stims on node 26: 140 
  Number of stims on node 10: 140 
  Number of stims on node 41: 140 
  Number of stims on node 32: 140 
  Number of stims on node 38: 140 
  Number of stims on node 29: 140 
  Number of stims on node 40: 140 
  Number of stims on node 30: 140 
  Number of stims on node 28: 140 
  Number of stims on node 34: 140 
  Number of stims on node 42: 140 
  Done; cell stims creation time = 0.10 s.
Recording 0 traces of 0 types on node 118
Recording 0 traces of 0 types on node 65
Recording 0 traces of 0 types on node 121
Recording 0 traces of 0 types on node 7
Recording 0 traces of 0 types on node 114
Recording 0 traces of 0 types on node 59
Recording 0 traces of 0 types on node 37
Recording 0 traces of 0 types on node 103
Recording 0 traces of 0 types on node 119
Recording 0 traces of 0 types on node 113
Recording 0 traces of 0 types on node 87
Recording 0 traces of 0 types on node 24
Recording 0 traces of 0 types on node 88
Recording 0 traces of 0 types on node 117
Recording 0 traces of 0 types on node 58
Recording 0 traces of 0 types on node 56
Recording 0 traces of 0 types on node 31
Recording 0 traces of 0 types on node 11
Recording 0 traces of 0 types on node 79
Recording 0 traces of 0 types on node 125
Recording 0 traces of 0 types on node 35
Recording 0 traces of 0 types on node 84
Recording 0 traces of 0 types on node 45
Recording 1 traces of 1 types on node 100
Recording 0 traces of 0 types on node 41
Recording 0 traces of 0 types on node 101
Recording 0 traces of 0 types on node 108
Recording 0 traces of 0 types on node 93
Recording 0 traces of 0 types on node 36
Recording 1 traces of 1 types on node 73
Recording 0 traces of 0 types on node 120
Recording 0 traces of 0 types on node 62
Recording 0 traces of 0 types on node 34
Recording 0 traces of 0 types on node 49
Recording 0 traces of 0 types on node 2
Recording 0 traces of 0 types on node 9
Recording 0 traces of 0 types on node 97
Recording 0 traces of 0 types on node 47
Recording 0 traces of 0 types on node 46
Recording 0 traces of 0 types on node 91
Recording 0 traces of 0 types on node 32
Recording 0 traces of 0 types on node 109
Recording 0 traces of 0 types on node 6
Recording 0 traces of 0 types on node 17
Recording 0 traces of 0 types on node 14
Recording 0 traces of 0 types on node 33
Recording 0 traces of 0 types on node 106
Recording 0 traces of 0 types on node 12
Recording 0 traces of 0 types on node 107
Recording 0 traces of 0 types on node 94
Recording 0 traces of 0 types on node 78
Recording 0 traces of 0 types on node 52
Recording 0 traces of 0 types on node 76
Recording 0 traces of 0 types on node 19
Recording 0 traces of 0 types on node 40
Recording 0 traces of 0 types on node 26
Recording 0 traces of 0 types on node 64
Recording 0 traces of 0 types on node 89
Recording 0 traces of 0 types on node 39
Recording 0 traces of 0 types on node 71
Recording 0 traces of 0 types on node 20
Recording 0 traces of 0 types on node 75
Recording 0 traces of 0 types on node 68
Recording 0 traces of 0 types on node 124
Recording 0 traces of 0 types on node 104
Recording 0 traces of 0 types on node 72
Recording 0 traces of 0 types on node 27
Recording 0 traces of 0 types on node 110
Recording 0 traces of 0 types on node 67
Recording 0 traces of 0 types on node 85
Recording 0 traces of 0 types on node 50
Recording 0 traces of 0 types on node 111
Recording 0 traces of 0 types on node 48
Recording 0 traces of 0 types on node 16
Recording 0 traces of 0 types on node 115
Recording 0 traces of 0 types on node 29
Recording 0 traces of 0 types on node 123
Recording 0 traces of 0 types on node 25
Recording 0 traces of 0 types on node 15
Recording 0 traces of 0 types on node 3
Recording 0 traces of 0 types on node 22
Recording 0 traces of 0 types on node 98
Recording 0 traces of 0 types on node 77
Recording 0 traces of 0 types on node 81
Recording 0 traces of 0 types on node 74
Recording 0 traces of 0 types on node 21
Recording 0 traces of 0 types on node 105
Recording 0 traces of 0 types on node 66
Recording 0 traces of 0 types on node 51
Recording 0 traces of 0 types on node 96
Recording 0 traces of 0 types on node 55
Recording 0 traces of 0 types on node 99
Recording 0 traces of 0 types on node 5
Recording 0 traces of 0 types on node 54
Recording 0 traces of 0 types on node 61
Recording 0 traces of 0 types on node 42
Recording 1 traces of 1 types on node 70
Recording 1 traces of 1 types on node 112
Recording 0 traces of 0 types on node 69
Recording 0 traces of 0 types on node 44
Recording 0 traces of 0 types on node 57
Recording 1 traces of 1 types on node 38
Recording 1 traces of 1 types on node 126
Recording 1 traces of 1 types on node 90
Recording 1 traces of 1 types on node 43
Recording 0 traces of 0 types on node 30
Recording 1 traces of 1 types on node 122
Recording 0 traces of 0 types on node 4
Recording 1 traces of 1 types on node 92
Recording 0 traces of 0 types on node 1
Recording 0 traces of 0 types on node 127
Recording 0 traces of 0 types on node 86
Recording 1 traces of 1 types on node 82
Recording 0 traces of 0 types on node 95
Recording 1 traces of 1 types on node 60
Recording 1 traces of 1 types on node 18
Recording 1 traces of 1 types on node 116
Recording 1 traces of 1 types on node 80
Recording 1 traces of 1 types on node 8
Recording 1 traces of 1 types on node 0
Recording 1 traces of 1 types on node 102
Recording 1 traces of 1 types on node 10
Recording 1 traces of 1 types on node 13
Recording 1 traces of 1 types on node 83
Recording 1 traces of 1 types on node 53
Recording 1 traces of 1 types on node 23
Recording 2 traces of 1 types on node 28
Recording 1 traces of 1 types on node 63
0.0s

Running simulation using NEURON for 600.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
0.6s
  Done; run time = 445.72 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 43.22 s.

Analyzing...
  Cells: 1048
  Connections: 227707 (217.28 per cell)
  Synaptic contacts: 1129654 (1077.91 per cell)
  Spikes: 5588 (8.89 Hz)
  Simulated time: 0.6 s; 128 workers
  Run time: 445.72 s
   L4_BP_cNAC_0 : 39.872 Hz
   L4_BTC_cNAC_1 : 35.778 Hz
   L4_NBC_cNAC_2 : 33.889 Hz
   L4_SSC_cADpyr_3 : 9.498 Hz
   L4_TPC_cADpyr_4 : 13.692 Hz
   L4_TPC_cADpyr_5 : 6.655 Hz
   L4_UPC_cADpyr_6 : 8.340 Hz
   VPM_sTC : 1.750 Hz
Saving output as /expanse/lustre/projects/csd403/fborges/v2_batch4/v2_batch4_0_data.pkl ... 
Finished saving!
  Done; saving time = 141.62 s.
Plotting 2D representation of network cell locations and connections...
Preparing LFP data...
Plotting LFP time series...
Preparing LFP data...
Preparing spectrogram data...
Plotting LFP spectrogram...
Plotting LFP electrode locations...
Plotting 3D cell shape ...
Preparing spike data...
Plotting raster...
Plotting recorded cell traces ... trace
  Done; plotting time = 13.71 s

Total time = 646.90 s
